# https://taskfile.dev

version: '3'

includes:
  echo: tasks/echo
  tf: tasks/terraform
  az: tasks/azurecli


tasks:
  
  tf-plan:
    - task: tf:plan
  
  condstates:
    - task: echo:conditional-statements
